packages/button/src/button.vue
test/unit/tests/button.test.js

use composition api refactoring button

Refactor button

---

migrate.md

docs: add migrate.md for track progress

---

packages/alert/index.js
packages/alert/src/main.vue
test/unit/tests/alert.test.js

Completed the refactoring of the Alert component with Vue 3 and wrote the test file.

refactor Alert component

---

build/bin/build-entry.js
packages/tag/src/tag.vue
test/unit/tests/tag.test.js

refactor Tag component

---

packages/backtop/src/main.vue

WIP: use vue3 refactoring backtop

---

packages/badge/src/main.vue
packages/message/src/main.vue

chore: code format badge

---

src/use/emitter.js
test/unit/tests/use/emitter.test.js

为了解决 #20 问题
实现了 on 方法，使用方式参考对应的单元测试
如果有更好的实现方式可以在讨论讨论
也可以在加一点单元测试验证这个逻辑哈

feat: support on method

---

README.md

Modify and add notes in README.md

---

.github/workflows/main.yml
package.json

为CI添加lint 和 prebuild检测功能

---

build/componentRalated.js

提交了一个分析组件间依赖关系的工具

---

.github/PULL_REQUEST_TEMPLATE.md
src/use/emitter.js
test/unit/tests/use/emitter.test.js

fix: update emitter add once function and test

---

packages/page-header/__tests__/pageHeader.spec.js
packages/page-header/src/main.vue

use composition api refactoring page-header

refactor:use composition api refactoring page-header

---

packages/notification/Notification.vue
packages/notification/main.js
packages/theme-chalk/src/notification.scss

完成 Notification 组件显示和隐藏时的过渡效果，效果和原组件已保持一致。
#69

feat: Update Notification

---

packages/row/__tests__/Row.spec.js
packages/row/src/row.js

fix: add Row unit test and passed

---

packages/main/__tests__/Main.spec.js

fix: update Main test

---

packages/header/Header.vue
packages/header/__tests__/Header.spec.js

refactor: refactor with composition api and added test to header

---

packages/notification/__tests__/Notification.spec.js

fix: update Notification and test

---

package.json
packages/timeline-item/__tests__/TimelineItem.spec.js

fix:timeline test case 

---

packages/avatar/__tests__/Avatar.spec.js

test:update avatar and test

---

packages/dialog/__tests__/Dialog.spec.js

test: update Dialog and test

---

packages/dialog/__tests__/Dialog.spec.js

test:updata dialog test again

---

packages/dialog/__tests__/Dialog.spec.js

fix: update Dialog and test

---

packages/checkbox-group/CheckboxGroup.vue
packages/checkbox-group/__tests__/checkbox-group.spec.js

checkbox: fix use emitter

---

packages/form-item/FormItem.vue
packages/form/Form.vue

请提交PR之前确认一下已通过
2. 测试通过
3. 没有相关的issue

fix: 若干警告信息

---

build/md-loader/config.js

修复 https://github.com/kkbjs/element3/issues/208
---
请提交PR之前确认一下已通过
2. 测试通过

fix: 修复官网markdown文档代码未正确高亮

---

packages/input-number/InputNumber.vue
packages/input-number/__tests__/InputNumber.spec.js

fix: update inputNumber and test

---

build/bin/build-entry.js
examples/docs/zh-CN/collapse.md
packages/collapse/__tests__/collapse.spec.js
packages/collapse/src/collapse-item.vue
packages/collapse/src/collapse.vue

refactor: refactor collapse collapse-item and add test

---

packages/upload/src/index.vue
packages/upload/src/upload-dragger.vue
packages/upload/src/upload-list.vue
packages/upload/src/upload.vue

refactor: Upload

---

packages/image/Image.vue
packages/image/__tests__/Image.spec.js

1.使用composition api改造Image.vue
2.升级相应的单元测试文件image.spec.js

refactor: Image.vue and update Image.spec.js

---

package.json

build: 升级 Vue 3 依赖版本

---

packages/menu/__tests__/Menu.spec.js

refactor: add menu test

---

examples/docs/zh-CN/popover.md
examples/docs/zh-CN/progress.md
examples/docs/zh-CN/rate.md
examples/docs/zh-CN/select.md
examples/docs/zh-CN/slider.md

fix: update 5 examples md

---

examples/docs/zh-CN/avatar.md
examples/docs/zh-CN/calendar.md
examples/docs/zh-CN/infiniteScroll.md

fix: avater ... md

---

examples/docs/zh-CN/switch.md
examples/docs/zh-CN/tabs.md
examples/docs/zh-CN/tag.md
examples/docs/zh-CN/timeline.md
packages/color-picker/src/components/picker-dropdown.vue
packages/tag/Tag.vue

docs: update switch & tabs & tag & timeline md document

---

examples/docs/zh-CN/date-picker.md
examples/docs/zh-CN/datetime-picker.md
examples/docs/zh-CN/dialog.md
examples/docs/zh-CN/drawer.md
examples/docs/zh-CN/input-number.md

fix: update doc and test

---

examples/docs/zh-CN/drawer.md

docs: update drawer.md

---

packages/radio-button/RadioButton.vue
packages/radio-group/RadioGroup.vue
packages/radio/Radio.vue

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 [issues/317](https://github.com/kkbjs/element3/issues/317)

fix: Radio、Radio-Group、Radio-Button already known bugs

---

examples/nav.config.json

chore: hide entry button for table、dataPicker、timePicker、datetimePicker 

---

examples/docs/zh-CN/message.md
packages/message/Message.vue
types/element3.d.ts
types/message.d.ts

https://github.com/kkbjs/element3/issues/292

docs: check message docs

---

examples/docs/en-US/link.md
examples/docs/es/link.md
examples/docs/fr-FR/link.md
examples/docs/zh-CN/link.md
examples/docs/zh-CN/notification.md
packages/link/__tests__/Link.spec.js
packages/notification/Notification.vue
test/unit/specs/link.spec.js
types/element3.d.ts
types/link.d.ts

fixed: Notification and test

---

examples/docs/en-US/link.md
examples/docs/es/link.md
examples/docs/fr-FR/link.md
examples/docs/zh-CN/link.md
packages/avatar/Avatar.vue
packages/link/__tests__/Link.spec.js
test/unit/specs/link.spec.js
types/avatar.d.ts
types/element3.d.ts
types/link.d.ts

fixed: update Avatar and test

---

examples/docs/zh-CN/tag.md
types/element3.d.ts
types/tag.d.ts

docs: check tag docs

---

examples/docs/zh-CN/message-box.md
packages/message-box/src/MessageBox.js
packages/message-box/src/MessageBox.vue
types/element3.d.ts
types/message-box.d.ts

https://github.com/kkbjs/element3/issues/293

check MessageBox doc

---

types/icon.d.ts

types(icon.d.ts): fix icon type  #348

---

contributors.json

chore: add contributor

---

examples/docs/zh-CN/steps.md
types/element3.d.ts
types/steps.d.ts
types/upload.d.ts

docs: updata upload/steps and test

---

packages/timeline/__tests__/Timeline.spec.js

test: update Timeline test

---

examples/docs/zh-CN/tree.md
packages/tree/Tree.vue
packages/tree/__tests__/entity/tree-node.spec.js
packages/tree/entity/TreeNode.js
types/tree.d.ts

types: update tree typesing

---

packages/checkbox-group/CheckboxGroup.vue
src/use/prop-utils.js

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 #365

fix: CheckboxGroup already known bugs

---

types/element3.d.ts

types: update element3.d.ts

---

packages/cascader-panel/CascaderNode.vue
packages/cascader-panel/CascaderPanel.vue

fix: fix Cascader error

---

packages/slider/Slider.vue

fix: slider fixbug

---

types/element3.d.ts
types/icon.d.ts
types/loading.d.ts
types/pagination.d.ts

types: update .d.ts

---

examples/docs/zh-CN/upload.md
packages/upload/src/index.vue
packages/upload/src/upload.vue

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 [#383](https://github.com/hug-sun/element3/issues/383)

fix(upload): problem with thumbnail display

---

build/bin/build-entry.js
examples/docs/zh-CN/form.md
examples/docs/zh-CN/input.md
src/entry.js

docs: checked input component

---

examples/docs/zh-CN/upload.md
packages/upload/src/index.vue

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 #391

fix: upload scope slot and named slot errors

---

packages/input-number/InputNumber.vue

请提交PR之前确认一下已通过
2. 测试通过
3. https://github.com/hug-sun/element3/issues/405

fix(inputNumber): fix warn when change input value

---

examples/docs/zh-CN/menu.md

docs: clean NavMenu warn

---

packages/image/Image.vue
packages/image/ImageViewer.vue

fix(Image): fix watch warn 

---

examples/demo-styles/container.scss
examples/docs/zh-CN/container.md

修复 #397 问题
请提交PR之前确认一下已通过
2. 测试通过

docs: Container doc style problem

---

packages/steps/src/steps.vue

fix(Steps): clear steps warn

---

examples/components/theme-configurator/editor/color-picker/src/main.vue
packages/autocomplete/src/autocomplete.vue
packages/date-picker/src/panel/date-range.vue
packages/date-picker/src/panel/date.vue
packages/date-picker/src/panel/month-range.vue
packages/date-picker/src/picker.vue
packages/dropdown/src/dropdown.vue
packages/table/src/filter-panel.vue

修复引用了旧文件 clickoutside的组件 ，utils/clickoutside 替换成 directives/clickoutside

refactor: replace old clickoutside file references

---

examples/docs/zh-CN/upload.md

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 #426

docs: user avatar upload example error

---

packages/button/tests/Button.spec.js

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 #423

test: Button.spec.js repeated tests and word errors

---

packages/button-group/__tests__/ButtonGroup.spec.js

test: add button-group test

---

examples/docs/zh-CN/border.md
examples/docs/zh-CN/menu.md
examples/docs/zh-CN/tabs.md
packages/notification/Notification.vue

docs: fix warn for  border.md

---

packages/link/Link.vue
packages/link/__tests__/Link.spec.js

Refactor Link components using composition api and add test cases

refactor(Link): refactor Link component and  Test case

---

packages/input/Input.vue
packages/tag/__tests__/Tag.spec.js

修复 #434 BUG
请提交PR之前确认一下已通过
2. 测试通过

fix(Input): fix Input style error

---

packages/divider/Divider.vue
packages/divider/__tests__/Divider.spec.js

change indexOf to includes in Divider.vue
change Chinese text to English text in Divider.spec.js

refactor(Divider): refactor validator in props & change language in test

---

packages/link/Link.vue

fix(Link): fix Link style problem

---

packages/card/Card.vue

refactor(Card): refactor card

---

packages/menu/MenuItem.vue
packages/menu/Submenu.vue

close：#452
修复 Menu组件选中样式不起效bug

fix: fixed bug where menu component selected style does not work

---

packages/avatar/Avatar.vue
packages/avatar/__tests__/Avatar.spec.js
packages/avatar/props.js
src/utils/__tests__/type.spec.js
src/utils/types.js

refactor(avatar): refactor avatar componet

---

packages/badge/Badge.vue

fix(avatar): fix default type

---

package.json

chore(package.json):  universal dependencies

---

packages/element3/packages/menu/Menu.vue
packages/element3/packages/menu/MenuCollapseTransition.vue

replace ctx with proxy in the menu component

fix: the proxy to replace ctx

---

packages/website/examples/play.js

请提交PR之前确认一下已通过
2. 测试通过
3. 如果有相关的issue，记得关联上 #488

chore(website): introduce component library error in dev:play environment

---

packages/element3/packages/dialog/Dialog.vue
packages/element3/packages/dialog/__tests__/Dialog.spec.js

请提交PR之前确认一下已通过
2. 测试通过
点击遮罩层不关闭dialog参数修复

fix(element3): dialog  don't close  when  click mask 

---

.github/workflows/issue-reply.yml

ci: add issue-reply

---

packages/element3/src/index.js

fix(ElDatePicker): Fix bugs caused by exporting incomplete components

---

.github/workflows/issue-reply.yml

ci: fix link

---

packages/element3/packages/loading/Loading.vue

fix(loading): loading component cannot show by directive way

---

packages/element3/packages/menu/MenuItem.vue

https://github.com/hug-sun/element3/issues/555

fix(menu): fixbug menu not show title when hover

---

packages/element3/packages/menu/Menu.vue
packages/element3/packages/menu/__tests__/Menu.spec.js
packages/website/src/play/index.vue

fix(Menu): not expand bug

---

packages/element3/types/element3.d.ts

2. 测试通过
3. 如果有相关的 issue，记得关联上 #568

fix: setupGlobalOptions not export types (hug-sun#568)

---

packages/element3/src/components/Steps/src/Step.vue
packages/element3/src/components/Steps/tests/Step.spec.js

feat(compiler): refactor steps icon and description

---

packages/element3/packages/tabs/Tabs.vue

fix(tabs): tabPosition is top layout bug (#582)

---

packages/element3/src/composables/popup.js

fix(Dialog): fix not modal bug (#577)

---

.github/workflows/main.yml
src/components/divider/Divider.vue
src/components/divider/__test__/__snapshots__/divider.spec.ts.snap
src/components/divider/index.md

| property | available value | default value |
|---|---|---|
| dividerStyle | solide \| dotted \| dashed \| double | solid |
| color | CSSPropertise | - |
| dark | boolean | false |

Divider: add new feature (dividerStyle|color|dark)

---

src/.vitepress/config.js
src/components/badge/Badge.vue
src/components/badge/__test__/__snapshots__/badge.spec.ts.snap
src/components/badge/__test__/badge.spec.ts
src/components/badge/index.md
src/components/badge/index.ts
src/index.ts
src/utils/types.ts

feat: badge

---

src/.vitepress/config.js
src/components/tag/Tag.vue
src/components/tag/__test__/tag.spec.ts
src/components/tag/index.md
src/components/tag/index.ts
src/index.ts

Feature tag

---

src/components/avatar/Avatar.vue
src/components/avatar/__test__/avatar.spec.ts
src/components/avatar/index.md
src/components/divider/Divider.vue
src/components/empty/Empty.vue
src/components/empty/__test__/empty.spec.ts
src/components/empty/index.md
src/theme/src/avatar.scss
src/theme/src/col.scss

Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

fix(col): sass file of col has deprecation waring
